print ("What is your name?")
firstname = input()
print ("What is your surname?")
surname = input()
print ("What is your favourite colour?")
fav_colour = input()
print ("How many pets do you have?")
num_pets = input()
print ("Hello,",firstname,surname,",your favourite colour is",fav_colour,"and you have",num_pets, "pets.")
